### ISSUE TITLE
在火狐上面拖动图片的话，会打开一个新窗口

### ISSUE THREAD

**Issue by bensamin** [winyuan/jtopo_topology#3]
![image](https://user-images.githubusercontent.com/24221343/49193863-ca1afb80-f3bb-11e8-8a0e-74dd9d70715e.png)
只要拖动图片就会新增一个窗口，解决方法是增加一个全局的取消默认事件
`
 document.body.ondrop =  (event)=> {
            event.preventDefault();
            event.stopPropagation();
        }
`

**Comment by winyuan** [comment]
感谢提出该bug并提供解决方案。
