### ISSUE TITLE
demo有bug, 连线不能进行拖动

### ISSUE THREAD

**Issue by tuotuogenjudi** [winyuan/jtopo_topology#6]

**Comment by hukaixuan2017** [comment]
好像是的，不能拖动

**Comment by hukaixuan2017** [comment]
线的 drag 的属性修改一下 draggable="true"

**Comment by hukaixuan2017** [comment]
> 线的 drag 的属性修改一下 draggable="true"

这个是错误的，线拖拽到舞台去就是张图片，不能修 draggable="true"，

**Comment by winyuan** [comment]
连线本来就不能拖动的，选中线的图标，先后点击两个节点，完成连线。
