### ISSUE TITLE
线的拖拽是怎么实现的

### ISSUE THREAD

**Issue by hukaixuan2017** [winyuan/jtopo_topology#8]
请教一下，我打开页面，在实例化的时候，将线也作为可以拖拽部分，
var nodes_line = $("[topo-div-type='topo-link']");
        var nodes_line = nodes_line.length;
        for (var i = 0; i < nodes_line; i++) {
            var text = $(nodes_line[i]).find("span").eq(0).text();
            editor.drag(nodes_line[i], document.getElementById('topology-canvas'), text);
        }
但是拖在在舞台区，就成了一个图片，请教一下这个怎么处理才能连线

**Comment by winyuan** [comment]
连线的拖拽逻辑不能这么做啊，连线是需要基于两个node的。
